// Code generated by protoc-gen-go.
// source: app/app.proto
// DO NOT EDIT!

/*
Package app is a generated protocol buffer package.

It is generated from these files:
	app/app.proto

It has these top-level messages:
	EmptyMessage
	AuthRequestMessage
	AuthResponseMessage
	KeyValMessage
	SettingsMessage
	UserMessage
*/
package app

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EmptyMessage struct {
}

func (m *EmptyMessage) Reset()                    { *m = EmptyMessage{} }
func (m *EmptyMessage) String() string            { return proto.CompactTextString(m) }
func (*EmptyMessage) ProtoMessage()               {}
func (*EmptyMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type AuthRequestMessage struct {
	Email    string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *AuthRequestMessage) Reset()                    { *m = AuthRequestMessage{} }
func (m *AuthRequestMessage) String() string            { return proto.CompactTextString(m) }
func (*AuthRequestMessage) ProtoMessage()               {}
func (*AuthRequestMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AuthRequestMessage) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthRequestMessage) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthResponseMessage struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *AuthResponseMessage) Reset()                    { *m = AuthResponseMessage{} }
func (m *AuthResponseMessage) String() string            { return proto.CompactTextString(m) }
func (*AuthResponseMessage) ProtoMessage()               {}
func (*AuthResponseMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AuthResponseMessage) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type KeyValMessage struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *KeyValMessage) Reset()                    { *m = KeyValMessage{} }
func (m *KeyValMessage) String() string            { return proto.CompactTextString(m) }
func (*KeyValMessage) ProtoMessage()               {}
func (*KeyValMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *KeyValMessage) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValMessage) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type SettingsMessage struct {
	Initialized bool   `protobuf:"varint,1,opt,name=initialized" json:"initialized,omitempty"`
	Debug       bool   `protobuf:"varint,2,opt,name=debug" json:"debug,omitempty"`
	LogLevel    string `protobuf:"bytes,3,opt,name=logLevel" json:"logLevel,omitempty"`
}

func (m *SettingsMessage) Reset()                    { *m = SettingsMessage{} }
func (m *SettingsMessage) String() string            { return proto.CompactTextString(m) }
func (*SettingsMessage) ProtoMessage()               {}
func (*SettingsMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SettingsMessage) GetInitialized() bool {
	if m != nil {
		return m.Initialized
	}
	return false
}

func (m *SettingsMessage) GetDebug() bool {
	if m != nil {
		return m.Debug
	}
	return false
}

func (m *SettingsMessage) GetLogLevel() string {
	if m != nil {
		return m.LogLevel
	}
	return ""
}

type UserMessage struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Password string `protobuf:"bytes,4,opt,name=password" json:"password,omitempty"`
	Role     string `protobuf:"bytes,5,opt,name=role" json:"role,omitempty"`
	Phone    string `protobuf:"bytes,6,opt,name=phone" json:"phone,omitempty"`
}

func (m *UserMessage) Reset()                    { *m = UserMessage{} }
func (m *UserMessage) String() string            { return proto.CompactTextString(m) }
func (*UserMessage) ProtoMessage()               {}
func (*UserMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UserMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserMessage) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserMessage) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserMessage) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *UserMessage) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func init() {
	proto.RegisterType((*EmptyMessage)(nil), "app.EmptyMessage")
	proto.RegisterType((*AuthRequestMessage)(nil), "app.AuthRequestMessage")
	proto.RegisterType((*AuthResponseMessage)(nil), "app.AuthResponseMessage")
	proto.RegisterType((*KeyValMessage)(nil), "app.KeyValMessage")
	proto.RegisterType((*SettingsMessage)(nil), "app.SettingsMessage")
	proto.RegisterType((*UserMessage)(nil), "app.UserMessage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for App service

type AppClient interface {
	Auth(ctx context.Context, in *AuthRequestMessage, opts ...grpc.CallOption) (*AuthResponseMessage, error)
	KeyValCreate(ctx context.Context, in *KeyValMessage, opts ...grpc.CallOption) (*EmptyMessage, error)
	KeyValRead(ctx context.Context, in *KeyValMessage, opts ...grpc.CallOption) (*KeyValMessage, error)
	KeyValUpdate(ctx context.Context, in *KeyValMessage, opts ...grpc.CallOption) (*EmptyMessage, error)
	KeyValDelete(ctx context.Context, in *KeyValMessage, opts ...grpc.CallOption) (*EmptyMessage, error)
}

type appClient struct {
	cc *grpc.ClientConn
}

func NewAppClient(cc *grpc.ClientConn) AppClient {
	return &appClient{cc}
}

func (c *appClient) Auth(ctx context.Context, in *AuthRequestMessage, opts ...grpc.CallOption) (*AuthResponseMessage, error) {
	out := new(AuthResponseMessage)
	err := grpc.Invoke(ctx, "/app.App/Auth", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) KeyValCreate(ctx context.Context, in *KeyValMessage, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := grpc.Invoke(ctx, "/app.App/KeyValCreate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) KeyValRead(ctx context.Context, in *KeyValMessage, opts ...grpc.CallOption) (*KeyValMessage, error) {
	out := new(KeyValMessage)
	err := grpc.Invoke(ctx, "/app.App/KeyValRead", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) KeyValUpdate(ctx context.Context, in *KeyValMessage, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := grpc.Invoke(ctx, "/app.App/KeyValUpdate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) KeyValDelete(ctx context.Context, in *KeyValMessage, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := grpc.Invoke(ctx, "/app.App/KeyValDelete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for App service

type AppServer interface {
	Auth(context.Context, *AuthRequestMessage) (*AuthResponseMessage, error)
	KeyValCreate(context.Context, *KeyValMessage) (*EmptyMessage, error)
	KeyValRead(context.Context, *KeyValMessage) (*KeyValMessage, error)
	KeyValUpdate(context.Context, *KeyValMessage) (*EmptyMessage, error)
	KeyValDelete(context.Context, *KeyValMessage) (*EmptyMessage, error)
}

func RegisterAppServer(s *grpc.Server, srv AppServer) {
	s.RegisterService(&_App_serviceDesc, srv)
}

func _App_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.App/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).Auth(ctx, req.(*AuthRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_KeyValCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyValMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).KeyValCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.App/KeyValCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).KeyValCreate(ctx, req.(*KeyValMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_KeyValRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyValMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).KeyValRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.App/KeyValRead",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).KeyValRead(ctx, req.(*KeyValMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_KeyValUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyValMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).KeyValUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.App/KeyValUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).KeyValUpdate(ctx, req.(*KeyValMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_KeyValDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyValMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).KeyValDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.App/KeyValDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).KeyValDelete(ctx, req.(*KeyValMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _App_serviceDesc = grpc.ServiceDesc{
	ServiceName: "app.App",
	HandlerType: (*AppServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _App_Auth_Handler,
		},
		{
			MethodName: "KeyValCreate",
			Handler:    _App_KeyValCreate_Handler,
		},
		{
			MethodName: "KeyValRead",
			Handler:    _App_KeyValRead_Handler,
		},
		{
			MethodName: "KeyValUpdate",
			Handler:    _App_KeyValUpdate_Handler,
		},
		{
			MethodName: "KeyValDelete",
			Handler:    _App_KeyValDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/app.proto",
}

func init() { proto.RegisterFile("app/app.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 444 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xcf, 0x6e, 0xd4, 0x30,
	0x10, 0xc6, 0xb5, 0x49, 0x5b, 0x2d, 0xd3, 0x6e, 0x29, 0x2e, 0x88, 0x28, 0x70, 0xa8, 0x7c, 0x42,
	0x45, 0x6a, 0x04, 0x1c, 0x90, 0xb8, 0x55, 0xfc, 0xb9, 0x00, 0x45, 0x0a, 0x2a, 0xf7, 0xa9, 0x32,
	0xca, 0x5a, 0xeb, 0xb5, 0x4d, 0xec, 0x2c, 0x0a, 0x88, 0x0b, 0x77, 0x4e, 0xdc, 0x79, 0x29, 0x5e,
	0x81, 0x07, 0x41, 0xb6, 0x13, 0xba, 0xd1, 0xee, 0x01, 0x6e, 0xf3, 0x8d, 0x67, 0x7e, 0x1e, 0xcf,
	0x97, 0xc0, 0x0c, 0x8d, 0x29, 0xd0, 0x98, 0x33, 0xd3, 0x68, 0xa7, 0x59, 0x8a, 0xc6, 0xe4, 0xf7,
	0x6b, 0xad, 0x6b, 0x49, 0x05, 0x1a, 0x51, 0xa0, 0x52, 0xda, 0xa1, 0x13, 0x5a, 0xd9, 0x58, 0xc2,
	0x0f, 0xe1, 0xe0, 0xe5, 0xd2, 0xb8, 0xee, 0x2d, 0x59, 0x8b, 0x35, 0xf1, 0x57, 0xc0, 0xce, 0x5b,
	0x37, 0x2f, 0xe9, 0x63, 0x4b, 0xd6, 0xf5, 0x59, 0x76, 0x1b, 0x76, 0x69, 0x89, 0x42, 0x66, 0x93,
	0x93, 0xc9, 0x83, 0x1b, 0x65, 0x14, 0x2c, 0x87, 0xa9, 0x41, 0x6b, 0x3f, 0xe9, 0xa6, 0xca, 0x92,
	0x70, 0xf0, 0x57, 0xf3, 0x87, 0x70, 0x1c, 0x39, 0xd6, 0x68, 0x65, 0x69, 0x0d, 0xe4, 0xf4, 0x82,
	0xd4, 0x00, 0x0a, 0x82, 0x3f, 0x85, 0xd9, 0x6b, 0xea, 0x3e, 0xa0, 0x1c, 0xca, 0x8e, 0x20, 0x5d,
	0x50, 0xd7, 0x17, 0xf9, 0xd0, 0x37, 0xae, 0x50, 0xb6, 0xd4, 0x5f, 0x14, 0x05, 0x27, 0xb8, 0xf9,
	0x9e, 0x9c, 0x13, 0xaa, 0xb6, 0x43, 0xeb, 0x09, 0xec, 0x0b, 0x25, 0x9c, 0x40, 0x29, 0x3e, 0x53,
	0x15, 0x10, 0xd3, 0x72, 0x3d, 0xe5, 0x51, 0x15, 0x5d, 0xb5, 0x75, 0x40, 0x4d, 0xcb, 0x28, 0xfc,
	0x63, 0xa4, 0xae, 0xdf, 0xd0, 0x8a, 0x64, 0x96, 0xc6, 0xc7, 0x0c, 0x9a, 0x7f, 0x9f, 0xc0, 0xfe,
	0xa5, 0xa5, 0x66, 0xb8, 0xe3, 0x10, 0x12, 0x51, 0xf5, 0xd3, 0x25, 0xa2, 0xba, 0x5e, 0x4f, 0xb2,
	0xbe, 0x1e, 0x06, 0x3b, 0x0a, 0x97, 0xd4, 0xd3, 0x42, 0x3c, 0x5a, 0xd9, 0xce, 0x78, 0x65, 0xbe,
	0xbe, 0xd1, 0x92, 0xb2, 0xdd, 0x58, 0xef, 0x63, 0x4f, 0x36, 0x73, 0xad, 0x28, 0xdb, 0x8b, 0xe4,
	0x20, 0x1e, 0xff, 0x4c, 0x21, 0x3d, 0x37, 0x86, 0x5d, 0xc0, 0x8e, 0x5f, 0x32, 0xbb, 0x7b, 0xe6,
	0x3d, 0xdf, 0xf4, 0x2d, 0xcf, 0xd6, 0x0e, 0x46, 0x46, 0xf0, 0xe3, 0x6f, 0xbf, 0x7e, 0xff, 0x48,
	0x66, 0x7c, 0x5a, 0xac, 0x1e, 0x15, 0xd8, 0xba, 0xf9, 0xb3, 0xc9, 0x29, 0x2b, 0xe1, 0x20, 0xfa,
	0xf0, 0xbc, 0x21, 0x74, 0xc4, 0x58, 0x68, 0x1f, 0x59, 0x93, 0xdf, 0x0a, 0xb9, 0xd1, 0x37, 0x73,
	0x2f, 0xb0, 0xee, 0xe4, 0x47, 0x9e, 0xb5, 0xa0, 0x6e, 0x85, 0xb2, 0xf8, 0xb2, 0xa0, 0xee, 0xab,
	0x67, 0x5e, 0x00, 0x44, 0x40, 0x49, 0x58, 0x6d, 0x25, 0x6e, 0xc9, 0xf1, 0x2c, 0x20, 0x19, 0xdb,
	0x40, 0x5e, 0xcf, 0x78, 0x69, 0xaa, 0xff, 0x9f, 0x91, 0x6f, 0x9d, 0xf1, 0xdd, 0xc0, 0x7c, 0x41,
	0x92, 0xfe, 0x9d, 0xd9, 0x0f, 0x79, 0xba, 0xc1, 0xbc, 0xda, 0x0b, 0x3f, 0xd7, 0x93, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xb0, 0x78, 0x64, 0x78, 0x90, 0x03, 0x00, 0x00,
}
