// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/app.proto

package pb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthRequestMessage struct {
	GrantType            string   `protobuf:"bytes,1,opt,name=grant_type,json=grantType,proto3" json:"grant_type,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequestMessage) Reset()         { *m = AuthRequestMessage{} }
func (m *AuthRequestMessage) String() string { return proto.CompactTextString(m) }
func (*AuthRequestMessage) ProtoMessage()    {}
func (*AuthRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a05ecb5db23acf21, []int{0}
}

func (m *AuthRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequestMessage.Unmarshal(m, b)
}
func (m *AuthRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequestMessage.Marshal(b, m, deterministic)
}
func (m *AuthRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequestMessage.Merge(m, src)
}
func (m *AuthRequestMessage) XXX_Size() int {
	return xxx_messageInfo_AuthRequestMessage.Size(m)
}
func (m *AuthRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequestMessage proto.InternalMessageInfo

func (m *AuthRequestMessage) GetGrantType() string {
	if m != nil {
		return m.GrantType
	}
	return ""
}

func (m *AuthRequestMessage) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthRequestMessage) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthResponseMessage struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	TokenType            string   `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	ExpiresIn            int64    `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponseMessage) Reset()         { *m = AuthResponseMessage{} }
func (m *AuthResponseMessage) String() string { return proto.CompactTextString(m) }
func (*AuthResponseMessage) ProtoMessage()    {}
func (*AuthResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a05ecb5db23acf21, []int{1}
}

func (m *AuthResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponseMessage.Unmarshal(m, b)
}
func (m *AuthResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponseMessage.Marshal(b, m, deterministic)
}
func (m *AuthResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponseMessage.Merge(m, src)
}
func (m *AuthResponseMessage) XXX_Size() int {
	return xxx_messageInfo_AuthResponseMessage.Size(m)
}
func (m *AuthResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponseMessage proto.InternalMessageInfo

func (m *AuthResponseMessage) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *AuthResponseMessage) GetTokenType() string {
	if m != nil {
		return m.TokenType
	}
	return ""
}

func (m *AuthResponseMessage) GetExpiresIn() int64 {
	if m != nil {
		return m.ExpiresIn
	}
	return 0
}

type UserMessage struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Role                 string   `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMessage) Reset()         { *m = UserMessage{} }
func (m *UserMessage) String() string { return proto.CompactTextString(m) }
func (*UserMessage) ProtoMessage()    {}
func (*UserMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a05ecb5db23acf21, []int{2}
}

func (m *UserMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMessage.Unmarshal(m, b)
}
func (m *UserMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMessage.Marshal(b, m, deterministic)
}
func (m *UserMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMessage.Merge(m, src)
}
func (m *UserMessage) XXX_Size() int {
	return xxx_messageInfo_UserMessage.Size(m)
}
func (m *UserMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMessage.DiscardUnknown(m)
}

var xxx_messageInfo_UserMessage proto.InternalMessageInfo

func (m *UserMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserMessage) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserMessage) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserMessage) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthRequestMessage)(nil), "pb.AuthRequestMessage")
	proto.RegisterType((*AuthResponseMessage)(nil), "pb.AuthResponseMessage")
	proto.RegisterType((*UserMessage)(nil), "pb.UserMessage")
}

func init() { proto.RegisterFile("pb/app.proto", fileDescriptor_a05ecb5db23acf21) }

var fileDescriptor_a05ecb5db23acf21 = []byte{
	// 306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xb1, 0x4e, 0xf3, 0x30,
	0x10, 0xc7, 0xd5, 0xb4, 0xdf, 0xa7, 0xe6, 0x5a, 0x18, 0x5c, 0x09, 0xa2, 0x8a, 0x4a, 0x90, 0x09,
	0x31, 0x34, 0x02, 0x36, 0x36, 0x46, 0x24, 0x58, 0xaa, 0x32, 0x57, 0x4e, 0x7b, 0x4a, 0xad, 0x16,
	0xfb, 0xf0, 0x39, 0x85, 0x0e, 0x2c, 0xbc, 0x02, 0x8f, 0xc6, 0x2b, 0xf0, 0x20, 0xc8, 0x76, 0x0a,
	0x42, 0x6c, 0x4c, 0xb9, 0xfb, 0xfd, 0x13, 0xfd, 0xee, 0x2e, 0xd0, 0xa7, 0xb2, 0x90, 0x44, 0x63,
	0xb2, 0xc6, 0x19, 0x91, 0x50, 0x39, 0x3c, 0xaa, 0x8c, 0xa9, 0xd6, 0x58, 0x48, 0x52, 0x85, 0xd4,
	0xda, 0x38, 0xe9, 0x94, 0xd1, 0x1c, 0xdf, 0xc8, 0x57, 0x20, 0xae, 0x6b, 0xb7, 0x9c, 0xe0, 0x63,
	0x8d, 0xec, 0xee, 0x90, 0x59, 0x56, 0x28, 0x46, 0x00, 0x95, 0x95, 0xda, 0xcd, 0xdc, 0x96, 0x30,
	0x6b, 0x1d, 0xb7, 0x4e, 0xd3, 0x49, 0x1a, 0xc8, 0x74, 0x4b, 0x28, 0x86, 0xd0, 0xad, 0x19, 0xad,
	0x96, 0x0f, 0x98, 0x25, 0x21, 0xfc, 0xea, 0x7d, 0x46, 0x92, 0xf9, 0xc9, 0xd8, 0x45, 0xd6, 0x8e,
	0xd9, 0xae, 0xcf, 0x37, 0x30, 0x88, 0x32, 0x26, 0xa3, 0x19, 0x77, 0xb6, 0x13, 0xe8, 0xcb, 0xf9,
	0x1c, 0x99, 0x67, 0xce, 0xac, 0x50, 0x37, 0xbe, 0x5e, 0x64, 0x53, 0x8f, 0xfc, 0x40, 0x21, 0x8b,
	0x03, 0x45, 0x67, 0x1a, 0x48, 0x18, 0x68, 0x04, 0x80, 0xcf, 0xa4, 0x2c, 0xf2, 0x4c, 0xe9, 0xa0,
	0x6d, 0x4f, 0xd2, 0x86, 0xdc, 0xe8, 0xfc, 0x05, 0x7a, 0xf7, 0x8c, 0x76, 0xe7, 0xdb, 0x87, 0x44,
	0x2d, 0x1a, 0x4b, 0xa2, 0x16, 0x7f, 0x5d, 0x47, 0x08, 0xe8, 0x84, 0x6f, 0x3a, 0x81, 0x87, 0xda,
	0x33, 0x6b, 0xd6, 0x98, 0xfd, 0x8b, 0xcc, 0xd7, 0x17, 0x53, 0xe8, 0xf8, 0xb5, 0xc5, 0x6d, 0xf3,
	0x3c, 0x18, 0x53, 0x39, 0xfe, 0x7d, 0xf5, 0xe1, 0xe1, 0x37, 0xff, 0x71, 0xa0, 0x7c, 0xf0, 0xfa,
	0xfe, 0xf1, 0x96, 0xec, 0xe5, 0xdd, 0x62, 0x73, 0x5e, 0xc8, 0xda, 0x2d, 0xaf, 0x5a, 0x67, 0xe5,
	0xff, 0xf0, 0x03, 0x2f, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x37, 0x67, 0x1e, 0xf2, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	Auth(ctx context.Context, in *AuthRequestMessage, opts ...grpc.CallOption) (*AuthResponseMessage, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Auth(ctx context.Context, in *AuthRequestMessage, opts ...grpc.CallOption) (*AuthResponseMessage, error) {
	out := new(AuthResponseMessage)
	err := c.cc.Invoke(ctx, "/pb.Auth/Auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	Auth(context.Context, *AuthRequestMessage) (*AuthResponseMessage, error)
}

// UnimplementedAuthServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (*UnimplementedAuthServer) Auth(ctx context.Context, req *AuthRequestMessage) (*AuthResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Auth not implemented")
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Auth/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Auth(ctx, req.(*AuthRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _Auth_Auth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/app.proto",
}
